services:
  # api:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #     # Only will build development stage from our dockerfile
  #     target: development
  #   volumes:
  #     - .:/usr/src/app
  #   env_file:
  #   - .env
  #   # Run a command against the development stage of the image
  #   command: npm run start:dev
  #   ports:
  #     - 3080:3080

  #   depends_on:
  #     - postgres
  
   postgres:
    image: postgis/postgis:14-3.2
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - bookcore-postgres:/var/lib/postgresql/data
volumes:
  bookcore-postgres: